### ISSUE TITLE
Use lookup table for ui and storage recipes

### ISSUE THREAD

**Issue by soofstad** [equinor/data-modelling-storage-service#287]
- [x] equinor/data-modelling-storage-service#282 
- [x] equinor/data-modelling-storage-service#292
- [x] equinor/dm-core-packages#34
- [x] https://github.com/equinor/dm-cli/issues/42
- [x] equinor/data-modelling-storage-service#298
- [x] equinor/data-modelling-storage-service#299
- [x] equinor/data-modelling-storage-service#300
- [x] equinor/data-modelling-storage-service#301
- [x] equinor/data-modelling-storage-service#302
- [x] equinor/create-dm-app#37

Suggestion:

-  A uiRecipe lookup entity for each app

```json
"type": "AppSettings",

"uiRecipePackage":  ["DMSS://data_soruce/recipesPakcage", "DMSS://data_soruce/anotherPackage"],



```

Each recipe package will have UiRecipeLinks as content. Subfolders should also be parsed
```json

[
{
"type": "RecipeLink",
"blueprintType": "myType",
"recipes": [
   {
    "type": "UiRecipe",
   "_id:" "12315-3464356-23464356"
   },
   {
    "type": "UiRecipe",
   "plugin:" "signal-plot"
   }
  ]}
]
```

UiREcipeLookupTable will be created in DMSS-internal (memory cached) upon import (created on client).

LookupTable:

```json
{
 "application1": {
      "uiRecipes": { 
        "myBlueprintType": [
              {
                 "type": "uiRecipe",
                 "plugin": "signal-plot"
              }
          ],
     "__default": []

},
      "storageRecipes": { }
   }
 "dmss": {
  "uiRecipes": {
   "system/SIMOS/Blueprint": {}
   "__default__" :  []
}

}


}

```
