### ISSUE TITLE
feature(clean-up): proper handling of non-contained elements on model and storage level

### ISSUE THREAD

**Issue by l3abak** [equinor/data-modelling-storage-service#374]
Non-contained elements on model and storage level need to be presented consistently. 

Two main assumptions.

 * Each entity is contained in one and only one place linked to an instance of Application blueprint. 
   * Root packages are contained in the DataStorage in an implicit way. 
   * If entity -A- dies (deleted) all entities contained -A- will be deleted, i.e. contained elements cannot exist without their container.  
   * Here model containment is of concern not storage containment. 
 * One can only point to an entity with relational address (for example path), i.e. pointing to a location of an entity, when using the single contained location.
   * all other references will be to the entity and not its location. 
   * relational path could be used point to any entity at any time, but the reference could only be stored after translating it to the entity reference (for example uuid) 

Let us consider the following models.

```
{name : Car,
 type: CORE:Blueprint,
  attributes: [
      {name: name,      attributeType:string, contaned:true},
      {name: plateNumber,  attributeType:number, contained:true},
      {name: engine,  attributeType:Engine, contained:true},
      {name: driver,  attributeType:Person, contaned:false, optional:true},
      {name: wheels,  attributeType:Wheel, dimension:*, contaned:true},
      {name: passengers, attributeType:Person, dimension:*, contaned:false}
   ]
}
```

```
{name : Engine,
 type: CORE:Blueprint,
  attributes: [
      {name: power,  attributeType:number, contained:true}
  ]
}
```

```
{name : Person,
 type: CORE:Blueprint,
  attributes: [
      {name: name,  attributeType:string, contained:true},
      {name: car,  attributeType:Car, contained:false},
  ]
}
```

```
{name : Wheel,
 type: CORE:Blueprint,
  attributes: [
      {name: diameter,  attributeType:number, contained:true}
  ]
}
```

```
{name : CarRentalCompany,
 type: CORE:Blueprint,
  attributes: [
      {name: name,  attributeType:string, contaned:true},
      {name: cars,  attributeType:Car, dimension:*, contaned:true},
      {name: customers, attributeType:Person, dimension:*, contaned:true}
   ]
}
```

```
{name : Reference,
 type: CORE:Blueprint,
  attributes: [
      {name: _id,  attributeType:string, optinal:true},
      {name: ref,  attributeType:string},
      {name: name,  attributeType:string, optional:true},
      {name: targetType,  attributeType:string, optional:true}
  ]
}

{name : StorageReference,
 type: CORE:Blueprint,
  _id: 1234123-1234-123-41-234,
  attributes: [
      {name: _id,  attributeType:string, optinal:true, description: "this is an optional uuid of the instance"},
      {name: storage_ref,  attributeType:string, optional:false},
      {name: name,  attributeType:string, optional:true},
      {name: targetType,  attributeType:string, optional:true}
  ]
}

```

Let us consider an entity of the CarRentalCompany with the following items:

```
{name : myrental,
 type: CarRentalCompany,
  cars: [ { name:volvo, 
              plateNumber:123J66,
              engine: {power: 1000},
              driver: { type: CORE:Reference,  ref: "dmss://appDS/{_id:myrental_id}.customers[0]",  },
              wheels:        [ { type: Wheel,  diameter: 50,  },  
                                    { type: Wheel,  diameter: 50,  },  
                                    { type: Wheel,  diameter: 50,  },  
                                    { type: Wheel,  diameter: 50,  }  ],  
              passengers: [ { type: CORE:Reference,  ref: "../../customers[0]",  },  
                                    { type: CORE:Reference,  ref: "../../customers{name:"Sarah Smith"}",  } ],   
            },
           {  name:toyota, 
              plateNumber:GHR3J66,
              engine: {power: 1500},
              driver: null,
              wheels:        [ { type: Wheel,  diameter: 50,  },  
                                    { type: Wheel,  diameter: 50,  },  
                                    { type: Wheel,  diameter: 50,  },  
                                    { type: Wheel,  diameter: 50,  }  ],  
              passengers: [  ],   
            }
      ],

    customers: [ {name: "John Smith",  car:{type:CORE:Reference, ref: "../../cars[0]"}],
                         {name: "Sarah Smith",  car:{type:CORE:Reference, ref: "../../cars{plateNumber:123J66}"] }
   ]
}
```

* When an entity is model-contained and storage-contained.
  * the entity will be placed and stored in the parent document, e.g. wheels in above example. 
* When an entity is model-non-contained it will automatically be storage-non-contained.
  * the entity is contained some where else.
  * in the location of the attribute, a Reference object will be stored which has a reference 
    * to the location where the entity is contained
    * directly to the entity is the entity has a direct reference in the underlying storage technology (uuid)
* When an entity is model-contained but storage-non-contained
  * the entity is contained here, but stored in a separate storage-cell (document for mongodb) with an access id (uuid for mongodb).
  * in the location of the attribute, a StorageReference object will be stored which has a reference 
    * to uuid of entity (e.g. storage_ref : dmss://appDS/234-345-1232354-3456)

References could have the following forms. 

Absolute references:

```
path: 

{protocol}://{data source name}/{name=root_package_name, type=Package, root:true}.content{name=package_name,  type=Package}.content{name=blueprint_name,  type=Blueprint}

dmss://system/SIMOS/Blueprint
dmss://system/{name:SIMOS, type=Package, root:true}.content{name:Blueprint,  type=Blueprint}


dmss://appDS/{name:instances, type=Package}.content{name:myrental}.cars[0].engine
dmss://appDS/instances/myrental.cars[0].engine
or
dmss://appDS/{_id:-myrental-id-}.cars[0].engine

dmss://appDS/models/carParts/Wheel
dmss://appDS/{name:models}.content{name:carParts}.content{name:Wheel}
or
dmss://appDS/{_id:-Wheel-id-}
```

Root Path:
Addressing elements on the same root (protocol and data storage).

```
/{_id:-myrental-id-}.cars[0].engine
/{name:instances}.content{name:myrental}.cars[0].engine


/{_id:-myrental-id-}
```

relative references:
all elements contained in one document, i.e. one contained object.

```
inside CarRentalCompany.cars[0]
../../customers[0]
../../customers[0]{name:"John Smith"}

```

StorageReferences could have the following forms:

```
{protocol}://{data source name}/id

StorageReference.storage_ref: dmss://appDS/2312134-12341-23412-4
StorageReference.storage_ref: azure-blob://2312134-12341-23412-4

equivalent for reference:

Reference.ref : dmss://appDS/{_id:2312134-12341-23412-4}


```

Let's say the cars in CarRentalCompany are "model-contained" but "storage-non-contained" then, 

```
{name : myrental,
 type: CarRentalCompany,
  cars: [ {type:CORE:StorageReference, storage_ref:dmss://appDS/-car0-id-},
           {  name:toyota, 
              plateNumber:GHR3J66,
              engine: {power: 1500},
              tdModel: {type:CORE:Reference, ref:azure://blob/{id:car0-id}, model_contained:true},
              driver: null,
              wheels:        [ { type: Wheel,  diameter: 50,  },  
                                    { type: Wheel,  diameter: 50,  },  
                                    { type: Wheel,  diameter: 50,  },  
                                    { type: Wheel,  diameter: 50,  }  ],  
              passengers: [  ],   
            }
      ],

    customers: [ {name: "John Smith",  car:{type:CORE:Reference, id:{myrental-id}.cars.0}],
                         {name: "John Smith",  car:{type:CORE:Reference, id:{myrental-id}.cars.0] }
   ]
}

```

where the car is stored in the storage system and accessible by id. 

```
{ name:volvo, 
  _id: -car0-id-,
              plateNumber:123J66,
              engine: {power: 1000},
              driver: { type: CORE:Reference,  ref: "dmss://appDS/{_id:myrental_id}.customers[0]",  },
              wheels:        [ { type: Wheel,  diameter: 50,  },  
                                    { type: Wheel,  diameter: 50,  },  
                                    { type: Wheel,  diameter: 50,  },  
                                    { type: Wheel,  diameter: 50,  }  ],  
              passengers: [ { type: CORE:Reference,  ref: "../../customers[0]",  },  
                                    { type: CORE:Reference,  ref: "../../customers{name:"Sarah Smith"}",  } ],   
            },
```

Here are the tasks:

- [x] https://github.com/equinor/data-modelling-storage-service/issues/387
- [x] https://github.com/equinor/data-modelling-storage-service/issues/388
- [ ] https://github.com/equinor/data-modelling-storage-service/issues/389
- [x] https://github.com/equinor/data-modelling-storage-service/issues/390
- [x] https://github.com/equinor/data-modelling-storage-service/issues/391
- [ ] https://github.com/equinor/data-modelling-storage-service/issues/392

**Comment by eoaksnes** [comment]
```
Rental Company 
  -> Cars[] (contained)
  -> Customers (contained)

Customer
  -> Car (not contained)
```

```
myCompany
  cars: [{car0},{car1},{car2}] 
  customers: [{customer1}]

customer1
   car:
      type: CORE:Reference
      id: ...myCompany.cars.2 
      type: SomeBlueprint
```

Expected behavior (acceptance criteria)
* Do not resolve non-contained attributes

What does non-contained on the model level means?
* If an attribute is non-contained on the model level it means that the entity does not own it (it points to it), then it does not make sense to have it contained on a storage level.

```
Example 1: Want to reference the same object
(company id)
{id}.cars.0.platenumber

Example 2: Want to be able to replace the engine
{id}.engine.power
```

Any complex object can have an id.

Should all objects that should be referenced directly be storage non-contained?

**Comment by eoaksnes** [comment]
Reference is of type Simos/Reference
   ref: str

PathReference extends Reference
   some of the path   

QueryReference  extends Reference
   query string

IdReference extends Reference
   protocol/ds/id

Reference is of type Simos/Reference
   ref: AbsolutePathReference | RelativePathReference | QueryReference |  IdReference 



what about dmss+query://?

**Comment by l3abak** [comment]
@eoaksnes I think we need to have another round of discussion on this. 
It seems we remember differently what we concluded for references. 
I am not sure which one is best right now either, but I am sure we need an easy way to understand we need to treat a string attribute as a reference.
